
services:
  info-backend: 
    container_name: recipe-backend
    build : .
    ports:
      - "5228:5000"
    volumes:
      - ./wwwroot:/app/wwwroot  
    networks:
      - recipe-network

  pg-db:
    container_name: pg-db
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=maRaNV
      - POSTGRES_DB=recipes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data   
     
    networks:
      - recipe-network

      
volumes:
  pgdata:


networks:
  recipe-network:
    driver: bridge