CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text NOT NULL,
    "Prenom" text NOT NULL,
    "Image" text NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Recipes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
"Ingredients" text NOT NULL,
"Instructions" text NOT NULL,


    "Image" text NOT NULL,
    "IdUser" integer NOT NULL,
    "IdCategory" integer NOT NULL,
    CONSTRAINT "PK_Recipes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Recipes_Categories_IdCategory" FOREIGN KEY ("IdCategory") REFERENCES "Categories" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Recipes_Users_IdUser" FOREIGN KEY ("IdUser") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Comments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Content" text NOT NULL,
    "CreatedAt" timestamp
    with
        time zone NOT NULL,
        "IdUser" integer NOT NULL,
        "IdRecipe" integer NOT NULL,
        CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Comments_Recipes_IdRecipe" FOREIGN KEY ("IdRecipe") REFERENCES "Recipes" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Comments_Users_IdUser" FOREIGN KEY ("IdUser") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Likes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdUser" integer NOT NULL,
    "IdRecipe" integer NOT NULL,
    CONSTRAINT "PK_Likes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Likes_Recipes_IdRecipe" FOREIGN KEY ("IdRecipe") REFERENCES "Recipes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Likes_Users_IdUser" FOREIGN KEY ("IdUser") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

ALTER TABLE "Users" ADD "IsAdmin" integer NOT NULL DEFAULT 0;

INSERT INTO
    "__EFMigrationsHistory" (
        "MigrationId",
        "ProductVersion"
    )
VALUES (
        '20240529215157_updates',
        '8.0.5'
    );

COMMIT;

ALTER TABLE "Categories" ADD "Image" text NOT NULL DEFAULT '';

INSERT INTO
    "__EFMigrationsHistory" (
        "MigrationId",
        "ProductVersion"
    )
VALUES (
        '20240618203812_add image to category',
        '8.0.5'
    );